trigger:
  branches:
    include:
    - master
pr:
  - master

resources:
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet:3.1.102
    endpoint: sspublicsbox

pool:
  vmImage: ubuntu-16.04

container: dotnetsdk

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: DotNetCoreCLI@2
  displayName: Restore Dependencies
  inputs:
    command: restore
    projects: '**/AcceptanceTests.Common/*.csproj'
    vstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: Create NuGet Packkage
  inputs:
    command: publish
    zipAfterPublish: false
    modifyOutputPath: false
    publishWebProjects: false
    projects: '**/AcceptanceTests.Common/*.csproj'
    outputDir: $(Build.ArtifactStagingDirectory)
    arguments: '--configuration release /p:Version="$(GitVersion.NuGetVersion)"'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: Push Package to VH NuGet Repo
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    publishVstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    versioningScheme: byBuildNumber
