trigger:
  branches:
    include:
    - master
pr:
  - master

pool:
  vmImage: ubuntu-16.04

container: mcr.microsoft.com/dotnet/core/sdk:3.1

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/AcceptanceTests.Common/*.csproj'
    vstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    zipAfterPublish: false
    modifyOutputPath: false
    publishWebProjects: false
    projects: '**/AcceptanceTests.Common/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)\ --configuration release /p:Version="$($gitversion.NuGetVersion)"'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    publishVstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    versioningScheme: byBuildNumber
