parameters:
- name: vstsFeed
  type: string
  default: 3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5

trigger:
  branches:
    include:
    - master
pr:
  - master

resources:
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet:6.0
    endpoint: sspublicsbox

pool:
  vmImage: ubuntu-latest

container: dotnetsdk

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5.10.3
  displayName: GitVersion
  inputs:
    configFilePath: GitVersion.yml

- task: DotNetCoreCLI@2
  displayName: Restore Dependencies
  inputs:
    command: restore
    projects: '**/AcceptanceTests.Common/*.csproj'
    vstsFeed: '${{ parameters.vstsFeed }}'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: Create NuGet Package
  inputs:
    projects: '**/AcceptanceTests.Common/*.csproj'
    arguments: '--configuration release /p:Version="$(GitVersion.NuGetVersion)" /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)"'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: Push Package to VH NuGet Repo
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    versioningScheme: byBuildNumber
