trigger:
  branches:
    include:
    - master
    - acceptance-tests
pr:
  - master

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: VIH-8979
      endpoint: hmcts

pool:
  vmImage: ubuntu-latest

jobs:
- job: Publish_Nuget_Packages
  displayName: Pulbish Nuget Packages
  steps:
  - template: templates/dotnet/publish-nuget-packages.yml@azTemplates
    parameters:
      nugetProjectPath: '**/AcceptanceTests.Common'
