trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
pr:
  - master

pool:
  name: Azure-VSTS-VS2017

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: UseDotNet@2
  displayName: 'Install latest dotnet'
  inputs:
    version: 3.1.102

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/AcceptanceTests.Common/*.csproj'
    vstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    zipAfterPublish: false
    modifyOutputPath: false
    publishWebProjects: false
    projects: '**/AcceptanceTests.Common/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)\ '
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/AcceptanceTests.Common/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)\ '   

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    publishVstsFeed: '3f69a23d-fbc7-4541-afc7-4cccefcad773/e48b2732-376c-4052-ba97-b28783c9bab5'
